# cloudbuild.yaml

steps:
  # Install dependencies
  - name: 'gcr.io/cloud-builders/nodejs'
    entrypoint: 'npm'
    args: ['ci']

  # Run tests (if applicable)
  - name: 'gcr.io/cloud-builders/nodejs'
    entrypoint: 'npm'
    args: ['test']

  # Build and push Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/dialogflow-app', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/dialogflow-app']

# You can add deployment steps based on the platform you choose.
